### ISSUE TITLE
Distinct sum in total

### ISSUE THREAD

**Issue by mortel** [ppdewolf/tauargus#12]
Hello community, 
I don't have an issue, but a question about tau-argus. 
I have a dataset where I don't want to have all datasets totaled, but only distinct datasets. 
Is this possible in Tau-Argus? And if so, could someone give me a hint for a solution?

Many thanks in advance and best regards!

**Comment by ppdewolf** [comment]
Moved your question to the dedicated UserSupport repository of the [sdcTools organization on GitHub](https://github.com/sdcTools/UserSupport) as [issue number 296](https://github.com/sdcTools/UserSupport/issues/296#issue-2651416441)
