### ISSUE TITLE
Controlled rounding via a batch file

### ISSUE THREAD

**Issue by olangsrud** [ppdewolf/tauargus#9]
bug?

Manual says RND(TabNo, RoundingBase, Steps, MaxTime,Partitions, StopRule) where StopRule: 1 = Rapid only, 2 = First feasible solution, 3 = optimal solution 

When writing batch file from the gui the values of StopRule become 0, 1 and 2 (not 1, 2 and 3).

After adding a line with SPECIFYTABLE and SAFETYRULE it become possible to run the batch file when StopRule is 1 or 2.

Using StopRule 0 (as in generated file when rapid) or 3 (optimal according to manual) results in error with text: Illegal value for max time

**Comment by ppdewolf** [comment]
This issue was moved to sdcTools/UserSupport#102
